# Generated by Django 3.2.8 on 2021-10-30 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.URLField(blank=True, default=None, max_length=1000, null=True),
        ),
    ]
